config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/movies", to: "movies#index" , as: "movies"
  post "/movies", to: "movies#create"
  get "movies/new", to: "movies#new"
  get "/movies/:id/edit", to: "movies#edit", as: "edit"
  get "/movies/:id", to: "movies#show", as: "movie"
  put "/movies/:id", to: "movies#update"
  delete "/movies/:id", to: "movies#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
        @movies = Movie.all()
    end

    def show
        @movie = Movie.find(params["id"])
    end

    def new

    end

    def create
        Movie.create(title: params["title"], run_time: params["run_time"], adult_rated: params["adult_rated"])
        redirect_to movies_path
    end

    def edit
        @movie = Movie.find(params["id"])
    end

    def update
        Movie.update(params["id"], title: params["title"], run_time: params["run_time"], adult_rated: params["adult_rated"])
        redirect_to movies_path
    end

    def destroy
        Movie.find(params["id"]).destroy
        redirect_to movies_path

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<form action="<%= movie_path(@movie.id) %>%" method="post">
<input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />
<input type="hidden" name="_method" value="put" />

<input placeholder="Movie Title" type="text" name="title" value="<%= @movie.title %>" />
<input placeholder="Movie Duration" type="number" name="run_time" value="<%= @movie.run_time %>"/>
 Adult rated? <input type="checkbox" name="adult_rated" checked="<%= @movie.adult_rated %>" />

<button type="submit">Update Movie</button> 
</form>

app/views/movies/index.html.erb
<h1>Movie Index</h1>

<table style="width:100%; border: 1px solid black; border-collapse: collapse;">
<tr>
<th style=" width: 50%; border: 1px solid black; border-collapse: collapse; background: dodgerblue; color: black; padding: 10px; font-size: 1.9vw;">Movie Name</th>
<th style=" width: 10%; border: 1px solid black; border-collapse: collapse; background: dodgerblue; color: black; padding: 10px; font-size: 1.9vw;">Movie Length</th>
<th style=" width: 10%; border: 1px solid black; border-collapse: collapse; background: dodgerblue; color: black; padding: 10px; font-size: 1.9vw;">Adult Rated?</th>
<th style=" width: 20%; border: 1px solid black; border-collapse: collapse; background: dodgerblue; color: black; padding: 10px; font-size: 1.9vw;">Options</th>
</tr>
<% for movie in @movies %>

<tr>
<td style="border: 1px solid black; border-collapse: collapse; padding: 10px;"><%= link_to movie.title, movie_path(movie.id) %></td>
<td style="border: 1px solid black; border-collapse: collapse; padding: 10px; text-align: center;"><%= t = Time.at(movie.run_time*60).utc.strftime("%H:%M")  %></td>
<td style="border: 1px solid black; border-collapse: collapse; padding: 10px; text-align: center;"><% if movie.adult_rated == true %>
MA15+
<% else  %>
PG
<% end %>
</td>
<td style="border: 1px solid black; border-collapse: collapse; padding: 10px; display: flex;"><form action="<%= movie_path(movie.id) %>" method="POST">
<input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />
<input type="hidden" name="_method" value="delete" />

<button type="submit">Delete</button>
</form>

<form action="<%link_to @edit, movie_path(movie.id)%>">


<button type="submit">Edit</button>
</form>





<%= button_to "view", movie_path(movie.id) %>


</td>




<% end %>
</tr>
</table>

app/views/movies/new.html.erb
<form action="/movies" method="POST">
<input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />
<input placeholder="Movie Title" type="text" name="title" />
<input placeholder="Movie Duration" type="number" name="run_time" />
 Adult rated? <input type="checkbox" name="adult_rated" />

<button type="submit">Create Movie</button>
</form>

app/views/movies/show.html.erb
<%= @movie.title %>
<%= link_to "Back", movies_path %>